import PDFDocument from "pdfkit";

export function generateDoctorReport(analysisData, stream) {
  const doc = new PDFDocument({ margin: 50 });

  // Stream PDF contents directly to the response stream
  doc.pipe(stream);

  // Document Title Header
  doc
    .fillColor("#0f7b63")
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("Medical Report Summary & Analysis", { align: "center" })
    .moveDown(0.2);

  doc
    .fillColor("#5b6875")
    .fontSize(10)
    .font("Helvetica")
    .text("Generated by AI Healthcare Triage Assistant", { align: "center" })
    .moveDown(1.5);

  // Horizontal separator line
  doc.strokeColor("#d8e4dd").lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke().moveDown(1);

  // Patient Info Block
  doc.fillColor("#172029").fontSize(13).font("Helvetica-Bold").text("Patient Information").moveDown(0.4);
  
  const info = analysisData.patient_info || {};
  doc.fontSize(10).font("Helvetica").fillColor("#172029");
  doc.text(`Name: ${info.name || "N/A"}`);
  doc.text(`Age: ${info.age || "N/A"}`);
  doc.text(`Gender: ${info.gender || "N/A"}`);
  doc.text(`Report Date: ${info.date || "N/A"}`).moveDown(1.5);

  // Risk Assessment Box
  const risk = analysisData.risk_assessment || {};
  const riskColors = {
    Emergency: "#b42318",
    Urgent: "#b7791f",
    Moderate: "#2563eb",
    "Low Risk": "#0f7b63"
  };
  const activeColor = riskColors[risk.level] || "#5b6875";

  doc.fontSize(13).font("Helvetica-Bold").text("Triage Risk Assessment").moveDown(0.4);
  
  // Custom font rendering for text
  doc.fontSize(10).font("Helvetica-Bold").fillColor(activeColor).text(`Urgency Level: ${risk.level || "Moderate"}`).fillColor("#172029");
  doc.font("Helvetica").text(`AI Health Score: ${analysisData.health_score || "N/A"}/100`);
  doc.text(`Reasoning: ${risk.reasoning || ""}`).moveDown(1.5);

  // Extracted Values Table
  const values = analysisData.extracted_values || [];
  if (values.length > 0) {
    doc.fontSize(13).font("Helvetica-Bold").text("Extracted Lab Values").moveDown(0.6);
    
    // Draw Table Headers
    const startY = doc.y;
    doc.fontSize(9).font("Helvetica-Bold").fillColor("#5b6875");
    doc.text("Parameter", 50, startY);
    doc.text("Value", 220, startY);
    doc.text("Reference Range", 340, startY);
    doc.text("Status", 460, startY);
    
    doc.strokeColor("#d8e4dd").lineWidth(0.5).moveTo(50, doc.y + 2).lineTo(550, doc.y + 2).stroke().moveDown(0.5);

    doc.font("Helvetica").fillColor("#172029");
    values.forEach((val) => {
      const rowY = doc.y;
      doc.text(val.parameter || "", 50, rowY);
      doc.text(`${val.value || ""} ${val.unit || ""}`, 220, rowY);
      doc.text(val.reference_range || "", 340, rowY);
      
      const statusColor = riskColors[val.status === "high" ? "Emergency" : val.status === "low" ? "Urgent" : "Low Risk"];
      doc.fillColor(statusColor).text((val.status || "normal").toUpperCase(), 460, rowY).fillColor("#172029");
      doc.moveDown(0.4);
    });
    doc.moveDown(1);
  }

  // AI Explanation
  doc.fontSize(13).font("Helvetica-Bold").text("Clinical AI Explanation").moveDown(0.4);
  doc.fontSize(10).font("Helvetica").text(analysisData.ai_explanation || "").moveDown(1.5);

  // Recommendations
  const recs = analysisData.recommendations || [];
  if (recs.length > 0) {
    doc.fontSize(13).font("Helvetica-Bold").text("Recommendations & Guidance").moveDown(0.4);
    doc.fontSize(10).font("Helvetica");
    recs.forEach((rec) => {
      doc.text(`• ${rec}`).moveDown(0.3);
    });
    doc.moveDown(1);
  }

  // Safety Disclaimer
  doc.strokeColor("#d8e4dd").lineWidth(0.5).moveTo(50, doc.y).lineTo(550, doc.y).stroke().moveDown(1);
  doc.fontSize(8).fillColor("#5b6875").text(
    "Disclaimer: This document is an automated analysis of a medical report for informational purposes. It does not replace professional medical diagnosis, treatment, or advice.",
    { align: "justify" }
  );

  doc.end();
}
